apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: deny-httpbin
spec:
  targetRefs:
    - kind: ServiceEntry
      group: networking.istio.io
      name: httpbin.org
  action: DENY
  rules:
    - from:
        - source:
            notNamespaces:
              - foo
